M48
; DRILL file {KiCad (5.99.0-12889-g70df3822b5)} date Wed Nov 17 13:47:16 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-11-17T13:47:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-12889-g70df3822b5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.5118Y-1.8701
X6.063Y-1.8701
T2
X5.7874Y-2.5717
T0
M30
